[project]
name = "Fluxed"
authors = [{name = "Rishabh Garg", email = "rishabh@rishabhgarg.dev"}]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "pytest"
]
